[package]
name = "quickreplace"
version = "0.1.0"
authors = ["jums <jummel19@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
text-colorizer = "1"
regex = "1"
